/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var counter = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("led waits ...")
						stateTimer = TimerActor("timer_s0", scope, context!!, "local_tout_s0", 5000.toLong())
					}
					 transition(edgeName="t05",targetState="tooLate",cond=whenTimeout("local_tout_s0"))   
					transition(edgeName="t06",targetState="handleLedCmd",cond=whenDispatchGuarded("ledCmd",{counter++ < 5 || counter > 8}))
				}	 
				state("handleLedCmd") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("ledCmd(X)"), Term.createTerm("ledCmd(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("led handleLedCmd: ${meta_msgArg(0)} counter=$counter")
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("tooLate") { //this:State
					action { //it:State
						println("Be faster, please ... ")
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
