/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IotRuntimeModule extends AbstractIotRuntimeModule {
}
