/* Generated by AN DISI Unibo */ 
package it.unibo.basicrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Basicrobot ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("ctxBasicRobot STARTED")
						solve("consult('basicRobotConfig')","") //set resVar	
						solve("robot(R)","") //set resVar	
						if(currentSolution.isSuccess()) println("robot( payloadArg(${getCurSol("R")} )")
					}
				}	 
			}
		}
}
