/* Generated by AN DISI Unibo */ 
package it.unibo.robotControl

import it.unibo.kactor.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class RobotControl ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t010",targetState="move",cond=whenEvent("local_buttonCmd"))
				}	 
				state("move") { //this:State
					action { //it:State
						forward("send","msg(moveforward)","clienttcp" ) 
						delay(1500) 
						forward("send","msg(movebackward)","clienttcp" ) 
					}
					 transition(edgeName="t111",targetState="move",cond=whenEvent("local_buttonCmd"))
					transition(edgeName="t112",targetState="handleCollision",cond=whenEvent("collision"))
				}	 
				state("handleCollision") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="move", cond=doswitch() )
				}	 
			}
		}
}
