/* Generated by AN DISI Unibo */ 
package it.unibo.simul

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Simul ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("s", "s(i1,on)" ,"neuron" ) 
						delay(100) 
						forward("s", "s(i2,on)" ,"neuron" ) 
						delay(100) 
						forward("s", "s(i2,off)" ,"neuron" ) 
						delay(100) 
						forward("s", "s(i2,on)" ,"neuron" ) 
					}
				}	 
			}
		}
}
