/* Generated by AN DISI Unibo */ 
package it.unibo.radartester

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Radartester ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(4000) 
						forward("polar", "p(50,10)" ,"radar" ) 
						delay(1000) 
						forward("polar", "p(50,20)" ,"radar" ) 
						delay(1000) 
						forward("polar", "p(50,30)" ,"radar" ) 
						delay(1000) 
						forward("polar", "p(50,40)" ,"radar" ) 
						delay(1000) 
						forward("polar", "p(50,50)" ,"radar" ) 
						delay(1000) 
						forward("polar", "p(50,60)" ,"radar" ) 
					}
				}	 
			}
		}
}
