/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class IotUiModule extends AbstractIotUiModule {
}
