/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.xtext.intro19.iot.IotPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends Message
{
} // Event
