/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see it.unibo.xtext.intro19.iot.IotFactory
 * @model kind="package"
 * @generated
 */
public interface IotPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iot";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unibo.it/xtext/intro19/Iot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iot";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IotPackage eINSTANCE = it.unibo.xtext.intro19.iot.impl.IotPackageImpl.init();

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.IotSystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.IotSystemImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getIotSystem()
   * @generated
   */
  int IOT_SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM__SPEC = 0;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl <em>System Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getIotSystemSpec()
   * @generated
   */
  int IOT_SYSTEM_SPEC = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM_SPEC__NAME = 0;

  /**
   * The feature id for the '<em><b>Mqtt Broker</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM_SPEC__MQTT_BROKER = 1;

  /**
   * The feature id for the '<em><b>Message</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM_SPEC__MESSAGE = 2;

  /**
   * The number of structural features of the '<em>System Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_SYSTEM_SPEC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.BrokerSpecImpl <em>Broker Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.BrokerSpecImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getBrokerSpec()
   * @generated
   */
  int BROKER_SPEC = 2;

  /**
   * The feature id for the '<em><b>Broker Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER_SPEC__BROKER_HOST = 0;

  /**
   * The feature id for the '<em><b>Broker Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER_SPEC__BROKER_PORT = 1;

  /**
   * The number of structural features of the '<em>Broker Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER_SPEC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.MessageImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Msg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MSG = 1;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.EventImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = MESSAGE__NAME;

  /**
   * The feature id for the '<em><b>Msg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__MSG = MESSAGE__MSG;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = MESSAGE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link it.unibo.xtext.intro19.iot.impl.DispatchImpl <em>Dispatch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.xtext.intro19.iot.impl.DispatchImpl
   * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getDispatch()
   * @generated
   */
  int DISPATCH = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISPATCH__NAME = MESSAGE__NAME;

  /**
   * The feature id for the '<em><b>Msg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISPATCH__MSG = MESSAGE__MSG;

  /**
   * The number of structural features of the '<em>Dispatch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISPATCH_FEATURE_COUNT = MESSAGE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.IotSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystem
   * @generated
   */
  EClass getIotSystem();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.xtext.intro19.iot.IotSystem#getSpec <em>Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Spec</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystem#getSpec()
   * @see #getIotSystem()
   * @generated
   */
  EReference getIotSystem_Spec();

  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.IotSystemSpec <em>System Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Spec</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystemSpec
   * @generated
   */
  EClass getIotSystemSpec();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystemSpec#getName()
   * @see #getIotSystemSpec()
   * @generated
   */
  EAttribute getIotSystemSpec_Name();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getMqttBroker <em>Mqtt Broker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mqtt Broker</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystemSpec#getMqttBroker()
   * @see #getIotSystemSpec()
   * @generated
   */
  EReference getIotSystemSpec_MqttBroker();

  /**
   * Returns the meta object for the containment reference list '{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Message</em>'.
   * @see it.unibo.xtext.intro19.iot.IotSystemSpec#getMessage()
   * @see #getIotSystemSpec()
   * @generated
   */
  EReference getIotSystemSpec_Message();

  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.BrokerSpec <em>Broker Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Broker Spec</em>'.
   * @see it.unibo.xtext.intro19.iot.BrokerSpec
   * @generated
   */
  EClass getBrokerSpec();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.xtext.intro19.iot.BrokerSpec#getBrokerHost <em>Broker Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Broker Host</em>'.
   * @see it.unibo.xtext.intro19.iot.BrokerSpec#getBrokerHost()
   * @see #getBrokerSpec()
   * @generated
   */
  EAttribute getBrokerSpec_BrokerHost();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.xtext.intro19.iot.BrokerSpec#getBrokerPort <em>Broker Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Broker Port</em>'.
   * @see it.unibo.xtext.intro19.iot.BrokerSpec#getBrokerPort()
   * @see #getBrokerSpec()
   * @generated
   */
  EAttribute getBrokerSpec_BrokerPort();

  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see it.unibo.xtext.intro19.iot.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.xtext.intro19.iot.Message#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibo.xtext.intro19.iot.Message#getName()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Name();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.xtext.intro19.iot.Message#getMsg <em>Msg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Msg</em>'.
   * @see it.unibo.xtext.intro19.iot.Message#getMsg()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Msg();

  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see it.unibo.xtext.intro19.iot.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for class '{@link it.unibo.xtext.intro19.iot.Dispatch <em>Dispatch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dispatch</em>'.
   * @see it.unibo.xtext.intro19.iot.Dispatch
   * @generated
   */
  EClass getDispatch();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IotFactory getIotFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.IotSystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.IotSystemImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getIotSystem()
     * @generated
     */
    EClass IOT_SYSTEM = eINSTANCE.getIotSystem();

    /**
     * The meta object literal for the '<em><b>Spec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_SYSTEM__SPEC = eINSTANCE.getIotSystem_Spec();

    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl <em>System Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getIotSystemSpec()
     * @generated
     */
    EClass IOT_SYSTEM_SPEC = eINSTANCE.getIotSystemSpec();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IOT_SYSTEM_SPEC__NAME = eINSTANCE.getIotSystemSpec_Name();

    /**
     * The meta object literal for the '<em><b>Mqtt Broker</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_SYSTEM_SPEC__MQTT_BROKER = eINSTANCE.getIotSystemSpec_MqttBroker();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_SYSTEM_SPEC__MESSAGE = eINSTANCE.getIotSystemSpec_Message();

    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.BrokerSpecImpl <em>Broker Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.BrokerSpecImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getBrokerSpec()
     * @generated
     */
    EClass BROKER_SPEC = eINSTANCE.getBrokerSpec();

    /**
     * The meta object literal for the '<em><b>Broker Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROKER_SPEC__BROKER_HOST = eINSTANCE.getBrokerSpec_BrokerHost();

    /**
     * The meta object literal for the '<em><b>Broker Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROKER_SPEC__BROKER_PORT = eINSTANCE.getBrokerSpec_BrokerPort();

    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.MessageImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__NAME = eINSTANCE.getMessage_Name();

    /**
     * The meta object literal for the '<em><b>Msg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MSG = eINSTANCE.getMessage_Msg();

    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.EventImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '{@link it.unibo.xtext.intro19.iot.impl.DispatchImpl <em>Dispatch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.xtext.intro19.iot.impl.DispatchImpl
     * @see it.unibo.xtext.intro19.iot.impl.IotPackageImpl#getDispatch()
     * @generated
     */
    EClass DISPATCH = eINSTANCE.getDispatch();

  }

} //IotPackage
