/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getMqttBroker <em>Mqtt Broker</em>}</li>
 *   <li>{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystemSpec()
 * @model
 * @generated
 */
public interface IotSystemSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystemSpec_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mqtt Broker</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mqtt Broker</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mqtt Broker</em>' containment reference.
   * @see #setMqttBroker(BrokerSpec)
   * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystemSpec_MqttBroker()
   * @model containment="true"
   * @generated
   */
  BrokerSpec getMqttBroker();

  /**
   * Sets the value of the '{@link it.unibo.xtext.intro19.iot.IotSystemSpec#getMqttBroker <em>Mqtt Broker</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mqtt Broker</em>' containment reference.
   * @see #getMqttBroker()
   * @generated
   */
  void setMqttBroker(BrokerSpec value);

  /**
   * Returns the value of the '<em><b>Message</b></em>' containment reference list.
   * The list contents are of type {@link it.unibo.xtext.intro19.iot.Message}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' containment reference list.
   * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystemSpec_Message()
   * @model containment="true"
   * @generated
   */
  EList<Message> getMessage();

} // IotSystemSpec
