/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.xtext.intro19.iot.IotSystem#getSpec <em>Spec</em>}</li>
 * </ul>
 *
 * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystem()
 * @model
 * @generated
 */
public interface IotSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Spec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec</em>' containment reference.
   * @see #setSpec(IotSystemSpec)
   * @see it.unibo.xtext.intro19.iot.IotPackage#getIotSystem_Spec()
   * @model containment="true"
   * @generated
   */
  IotSystemSpec getSpec();

  /**
   * Sets the value of the '{@link it.unibo.xtext.intro19.iot.IotSystem#getSpec <em>Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spec</em>' containment reference.
   * @see #getSpec()
   * @generated
   */
  void setSpec(IotSystemSpec value);

} // IotSystem
