/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.validation;

import it.unibo.xtext.intro19.validation.AbstractIotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotValidator extends AbstractIotValidator {
}
