/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ui;

import com.google.inject.Injector;
import it.unibo.xtext.intro19.Iot.ui.internal.IotActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IotActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IotActivator activator = IotActivator.getInstance();
		return activator != null ? activator.getInjector(IotActivator.IT_UNIBO_XTEXT_INTRO19_IOT) : null;
	}

}
