/* Generated by AN DISI Unibo */ 
package it.unibo.control

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Control ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t00",targetState="sOn",cond=whenEvent("local_buttonCmd"))
				}	 
				state("sOn") { //this:State
					action { //it:State
						emit("ledCmd", "ledCmd(on)" ) 
						TimerActor("timer", scope, context!!, "local_tout_sOn", 500.toLong())
					}
					 transition(edgeName="t11",targetState="sOff",cond=whenTimeout("local_tout_sOn"))   
					transition(edgeName="t12",targetState="s0",cond=whenEvent("local_buttonCmd"))
				}	 
				state("sOff") { //this:State
					action { //it:State
						emit("ledCmd", "ledCmd(off)" ) 
						TimerActor("timer", scope, context!!, "local_tout_sOff", 500.toLong())
					}
					 transition(edgeName="t23",targetState="sOn",cond=whenTimeout("local_tout_sOff"))   
					transition(edgeName="t24",targetState="s0",cond=whenEvent("local_buttonCmd"))
				}	 
			}
		}
}
