/* Generated by AN DISI Unibo */ 
package it.unibo.terminal1n

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Terminal1n ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("terminal1n idle")
					}
					 transition(edgeName="t01",targetState="work",cond=whenEvent("fired"))
				}	 
				state("work") { //this:State
					action { //it:State
						println("terminal1n work")
						forward("s", "s(i1)" ,"neuron" ) 
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
