/* Generated by AN DISI Unibo */ 
package it.unibo.g521support

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class G521support ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "init"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("g521support actor STARTS ... ")
						 Runtime.getRuntime().exec("sudo python robotCmdExec.py > cmdExecOut.txt") 
					}
					 transition(edgeName="t012",targetState="end",cond=whenEvent("pythonEnd"))
				}	 
				state("end") { //this:State
					action { //it:State
						println("g521support actor ENDS ... ")
					}
				}	 
			}
		}
}
