/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ui.tests;

import com.google.inject.Injector;
import it.unibo.xtext.intro19.Iot.ui.internal.IotActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IotActivator.getInstance().getInjector("it.unibo.xtext.intro19.Iot");
	}

}
