/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot.impl;

import it.unibo.xtext.intro19.iot.Event;
import it.unibo.xtext.intro19.iot.IotPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EventImpl extends MessageImpl implements Event
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotPackage.Literals.EVENT;
  }

} //EventImpl
