/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.iot.impl;

import it.unibo.xtext.intro19.iot.BrokerSpec;
import it.unibo.xtext.intro19.iot.IotPackage;
import it.unibo.xtext.intro19.iot.IotSystemSpec;
import it.unibo.xtext.intro19.iot.Message;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Spec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl#getMqttBroker <em>Mqtt Broker</em>}</li>
 *   <li>{@link it.unibo.xtext.intro19.iot.impl.IotSystemSpecImpl#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IotSystemSpecImpl extends MinimalEObjectImpl.Container implements IotSystemSpec
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getMqttBroker() <em>Mqtt Broker</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMqttBroker()
   * @generated
   * @ordered
   */
  protected BrokerSpec mqttBroker;

  /**
   * The cached value of the '{@link #getMessage() <em>Message</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected EList<Message> message;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IotSystemSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotPackage.Literals.IOT_SYSTEM_SPEC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotPackage.IOT_SYSTEM_SPEC__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BrokerSpec getMqttBroker()
  {
    return mqttBroker;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMqttBroker(BrokerSpec newMqttBroker, NotificationChain msgs)
  {
    BrokerSpec oldMqttBroker = mqttBroker;
    mqttBroker = newMqttBroker;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER, oldMqttBroker, newMqttBroker);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMqttBroker(BrokerSpec newMqttBroker)
  {
    if (newMqttBroker != mqttBroker)
    {
      NotificationChain msgs = null;
      if (mqttBroker != null)
        msgs = ((InternalEObject)mqttBroker).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER, null, msgs);
      if (newMqttBroker != null)
        msgs = ((InternalEObject)newMqttBroker).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER, null, msgs);
      msgs = basicSetMqttBroker(newMqttBroker, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER, newMqttBroker, newMqttBroker));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Message> getMessage()
  {
    if (message == null)
    {
      message = new EObjectContainmentEList<Message>(Message.class, this, IotPackage.IOT_SYSTEM_SPEC__MESSAGE);
    }
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER:
        return basicSetMqttBroker(null, msgs);
      case IotPackage.IOT_SYSTEM_SPEC__MESSAGE:
        return ((InternalEList<?>)getMessage()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IotPackage.IOT_SYSTEM_SPEC__NAME:
        return getName();
      case IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER:
        return getMqttBroker();
      case IotPackage.IOT_SYSTEM_SPEC__MESSAGE:
        return getMessage();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IotPackage.IOT_SYSTEM_SPEC__NAME:
        setName((String)newValue);
        return;
      case IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER:
        setMqttBroker((BrokerSpec)newValue);
        return;
      case IotPackage.IOT_SYSTEM_SPEC__MESSAGE:
        getMessage().clear();
        getMessage().addAll((Collection<? extends Message>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IotPackage.IOT_SYSTEM_SPEC__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER:
        setMqttBroker((BrokerSpec)null);
        return;
      case IotPackage.IOT_SYSTEM_SPEC__MESSAGE:
        getMessage().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IotPackage.IOT_SYSTEM_SPEC__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IotPackage.IOT_SYSTEM_SPEC__MQTT_BROKER:
        return mqttBroker != null;
      case IotPackage.IOT_SYSTEM_SPEC__MESSAGE:
        return message != null && !message.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //IotSystemSpecImpl
