/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/unibo/xtext/intro19/parser/antlr/internal/InternalIot.tokens");
	}
}
