/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ide;

import it.unibo.xtext.intro19.ide.AbstractIotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IotIdeModule extends AbstractIotIdeModule {
}
