/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unibo.xtext.intro19.IotRuntimeModule;
import it.unibo.xtext.intro19.IotStandaloneSetup;
import it.unibo.xtext.intro19.ide.IotIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IotIdeSetup extends IotStandaloneSetup {
  @Override
  public Injector createInjector() {
    IotRuntimeModule _iotRuntimeModule = new IotRuntimeModule();
    IotIdeModule _iotIdeModule = new IotIdeModule();
    return Guice.createInjector(Modules2.mixin(_iotRuntimeModule, _iotIdeModule));
  }
}
