/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class IotScopeProvider extends AbstractIotScopeProvider {

}
