/* Generated by AN DISI Unibo */ 
package it.unibo.worker

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Worker ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		var mapEmpty    = false
		val mapname     = "roomMbot" //yyy  
		var Curmove     = "" 
		var curmoveIsForward = false 
		
		//REAL ROBOT
		var StepTime   = 1000 	 
		var PauseTime  = 500 
		
		//VIRTUAL ROBOT
		//var StepTime   = 330	//for virtual
		//var PauseTime  = 500
		
		var PauseTimeL  = PauseTime.toLong()
		
		var Tback       = 0
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						itunibo.coap.client.resourceObserverCoapClient.create( "coap://localhost:5683/resourcemodel"  )
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.moveUtils.loadRoomMap(myself ,mapname )
						itunibo.planner.moveUtils.showCurrentRobotState(  )
							val MapStr =  itunibo.planner.plannerUtil.getMapOneLine()  
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
					}
					 transition( edgeName="goto",targetState="doWork", cond=doswitch() )
				}	 
				state("doWork") { //this:State
					action { //it:State
						println("&&&  worker WAITS")
					}
					 transition(edgeName="t09",targetState="setGoalAndDo",cond=whenDispatch("moveButlerTo"))
				}	 
				state("setGoalAndDo") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveButlerTo(X,Y,D)"), Term.createTerm("moveButlerTo(X,Y,D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								storeCurrentMessageForReply()
								itunibo.planner.plannerUtil.setGoal( payloadArg(0), payloadArg(1)  )
								itunibo.planner.moveUtils.doPlan(myself)
						}
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("executePlannedActions") { //this:State
					action { //it:State
						solve("retract(move(M))","") //set resVar	
						if(currentSolution.isSuccess()) { Curmove = getCurSol("M").toString() 
						              curmoveIsForward=(Curmove == "w")
						 }
						else
						{ Curmove = ""; curmoveIsForward=false
						 }
					}
					 transition( edgeName="goto",targetState="checkAndDoAction", cond=doswitchGuarded({(Curmove.length>0) }) )
					transition( edgeName="goto",targetState="goalOk", cond=doswitchGuarded({! (Curmove.length>0) }) )
				}	 
				state("goalOk") { //this:State
					action { //it:State
							val MapStr =  itunibo.planner.plannerUtil.getMapOneLine()  
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
						replyToCaller("exploreStepOk", "exploreStepOk")
					}
					 transition( edgeName="goto",targetState="doWork", cond=doswitch() )
				}	 
				state("checkAndDoAction") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="doForwardMove", cond=doswitchGuarded({curmoveIsForward}) )
					transition( edgeName="goto",targetState="doTheMove", cond=doswitchGuarded({! curmoveIsForward}) )
				}	 
				state("doTheMove") { //this:State
					action { //it:State
						if(Curmove.equals("a")){ itunibo.planner.moveUtils.rotateLeft90(myself)
						 println("		PLEASE TUNE THE ROTATION LEFT" ); readLine() 
						 }
						if(Curmove.equals("d")){ itunibo.planner.moveUtils.rotateRight90(myself)
						 println("		PLEASE TUNE THE ROTATION RIGHT" ); readLine() 
						 }
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("doForwardMove") { //this:State
					action { //it:State
						delay(PauseTimeL)
						itunibo.planner.moveUtils.attemptTomoveAhead(myself ,StepTime )
					}
					 transition(edgeName="t010",targetState="handleStepOk",cond=whenDispatch("stepOk"))
					transition(edgeName="t011",targetState="hadleStepFail",cond=whenDispatch("stepFail"))
				}	 
				state("handleStepOk") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.updateMapAfterAheadOk(myself)
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("hadleStepFail") { //this:State
					action { //it:State
						solve("retractall(move(M))","") //set resVar	
						if( checkMsgContent( Term.createTerm("stepFail(R,T)"), Term.createTerm("stepFail(Obs,Time)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								Tback=payloadArg(1).toString().toInt() / 4 
								println("		worker OBSTACLE TABLE FOUND $Tback / ${payloadArg(1).toString()} ")
						}
						itunibo.planner.moveUtils.backToCompensate(myself ,Tback, Tback )
						itunibo.planner.moveUtils.setObstacleOnCurrentDirection(myself)
						replyToCaller("exploreStepFail", "exploreStepFail")
					}
					 transition( edgeName="goto",targetState="doWork", cond=doswitch() )
				}	 
			}
		}
}
