/* Generated by AN DISI Unibo */ 
package it.unibo.ledmqtt

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Ledmqtt ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						resources.myLedSegm.create()
					}
					 transition( edgeName="goto",targetState="waitLedCmd", cond=doswitch() )
				}	 
				state("waitLedCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t05",targetState="handleLedCmd",cond=whenDispatch("ledCmd"))
				}	 
				state("handleLedCmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ledCmd(X)"), Term.createTerm("ledCmd(on)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								resources.myLedSegm.turnOn()
						}
						if( checkMsgContent( Term.createTerm("ledCmd(X)"), Term.createTerm("ledCmd(off)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								resources.myLedSegm.turnOff()
						}
					}
					 transition( edgeName="goto",targetState="waitLedCmd", cond=doswitch() )
				}	 
			}
		}
}
