/* Generated by AN DISI Unibo */ 
package it.unibo.robotmindnomvc

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotmindnomvc ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var obstacle = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("ROBOT MIND STARTED")
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('resourceModel.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitForEvents", cond=doswitch() )
				}	 
				state("waitForEvents") { //this:State
					action { //it:State
					}
					 transition(edgeName="t00",targetState="handleCmd",cond=whenEvent("userCmd"))
					transition(edgeName="t01",targetState="handleEnvCond",cond=whenEvent("envCond"))
					transition(edgeName="t02",targetState="handleSonarEnv",cond=whenEvent("sonar"))
					transition(edgeName="t03",targetState="handleSonarRobot",cond=whenEvent("sonarRobot"))
				}	 
				state("handleCmd") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("userCmd(CMD)"), Term.createTerm("userCmd(CMD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("robotCmd", "robotCmd(${payloadArg(0)})" ,"basicrobot" ) 
								solve("action(robot,move(${payloadArg(0)}))","") //set resVar	
								solve("model(A,robot,STATE)","") //set resVar	
								val RobotState = getCurSol("STATE") 
								emit("modelContent", "content(robot($RobotState))" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitForEvents", cond=doswitch() )
				}	 
				state("handleEnvCond") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("envCond(CONDTYPE)"), Term.createTerm("envCond(CMD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("robotCmd", "robotCmd(h)" ,"basicrobot" ) 
								itunibo.robot.resourceModelSupport.updateModel(myself ,"h" )
						}
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="waitForEvents", cond=doswitch() )
				}	 
				state("handleSonarRobot") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("sonar(DISTANCE)"), Term.createTerm("sonar(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								obstacle = Integer.parseInt( payloadArg(0) ) < 10 
						}
					}
					 transition( edgeName="goto",targetState="handeObstacle", cond=doswitchGuarded({obstacle}) )
					transition( edgeName="goto",targetState="waitForEvents", cond=doswitchGuarded({! obstacle}) )
				}	 
				state("handeObstacle") { //this:State
					action { //it:State
						println("robotmindnomvc handeObstacle: going back START")
						forward("robotCmd", "robotCmd(s)" ,"basicrobot" ) 
						itunibo.robot.resourceModelSupport.updateModel(myself ,"s" )
						delay(300) 
						println("robotmindnomvc handeObstacle: going back STOP")
						forward("robotCmd", "robotCmd(h)" ,"basicrobot" ) 
						itunibo.robot.resourceModelSupport.updateModel(myself ,"h" )
					}
					 transition( edgeName="goto",targetState="waitForEvents", cond=doswitch() )
				}	 
				state("handleSonarEnv") { //this:State
					action { //it:State
						println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
						println("$name in ${currentState.stateName} | $currentMsg")
						println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
					}
					 transition( edgeName="goto",targetState="waitForEvents", cond=doswitch() )
				}	 
			}
		}
}
