/* Generated by AN DISI Unibo */ 
package it.unibo.butlerfridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Butlerfridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("&&&  butlertask STARTED  ")
					}
					 transition(edgeName="t05",targetState="execTask",cond=whenDispatch("startTask"))
				}	 
				state("execTask") { //this:State
					action { //it:State
					}
				}	 
			}
		}
}
