/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.ui;

import it.unibo.xtext.intro19.ui.AbstractIotUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IotUiModule extends AbstractIotUiModule {
  public IotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
