/*
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIotScopeProvider extends DelegatingScopeProvider {
}
