/* Generated by AN DISI Unibo */ 
package it.unibo.a

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class A ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("a idel")
					}
					 transition(edgeName="t00",targetState="inpu1On",cond=whenEvent("input1on"))
					transition(edgeName="t01",targetState="inpu2On",cond=whenEvent("input2on"))
				}	 
				state("inpu1On") { //this:State
					action { //it:State
						println("a input1on")
					}
					 transition(edgeName="t02",targetState="s0",cond=whenEvent("input1off"))
					transition(edgeName="t03",targetState="firing",cond=whenEvent("input2on"))
				}	 
				state("inpu2On") { //this:State
					action { //it:State
						println("a input2on")
					}
					 transition(edgeName="t04",targetState="s0",cond=whenEvent("input2off"))
					transition(edgeName="t05",targetState="firing",cond=whenEvent("input1on"))
				}	 
				state("firing") { //this:State
					action { //it:State
						println("a firing")
					}
					 transition(edgeName="t06",targetState="inpu2On",cond=whenEvent("input1off"))
					transition(edgeName="t07",targetState="inpu1On",cond=whenEvent("input2off"))
				}	 
			}
		}
}
