/**
 * generated by Xtext 2.16.0
 */
package it.unibo.xtext.intro19;

import it.unibo.xtext.intro19.AbstractIotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotRuntimeModule extends AbstractIotRuntimeModule {
}
