/* Generated by AN DISI Unibo */ 
package it.unibo.blsmqttcontrol

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Blsmqttcontrol ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("blsmqttcontrol WAITS")
					}
					 transition(edgeName="t00",targetState="turnOn",cond=whenEvent("buttonCmd"))
				}	 
				state("turnOn") { //this:State
					action { //it:State
						forward("ledCmd", "ledCmd(on)" ,"ledmqtt" ) 
						emit("ledCmdEv", "ledCmd(on)" ) 
						stateTimer = TimerActor("timer_turnOn", scope, context!!, "local_tout_turnOn", 200.toLong())
					}
					 transition(edgeName="t11",targetState="turnOff",cond=whenTimeout("local_tout_turnOn"))   
					transition(edgeName="t12",targetState="s0",cond=whenEvent("buttonCmd"))
				}	 
				state("turnOff") { //this:State
					action { //it:State
						forward("ledCmd", "ledCmd(off)" ,"ledmqtt" ) 
						emit("ledCmdEv", "ledCmd(off)" ) 
						stateTimer = TimerActor("timer_turnOff", scope, context!!, "local_tout_turnOff", 200.toLong())
					}
					 transition(edgeName="t23",targetState="turnOn",cond=whenTimeout("local_tout_turnOff"))   
					transition(edgeName="t24",targetState="s0",cond=whenEvent("buttonCmd"))
				}	 
				state("checkUser") { //this:State
					action { //it:State
						println("Are you still here? ")
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
